{
 "title": "CampusFix Monitoring",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}